/*
 Navicat MySQL Data Transfer

 Source Server         : mysql
 Source Server Type    : MySQL
 Source Server Version : 80033
 Source Host           : localhost:3306
 Source Schema         : tie_bar_lower

 Target Server Type    : MySQL
 Target Server Version : 80033
 File Encoding         : 65001

 Date: 27/07/2023 18:21:35
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for bar_rank
-- ----------------------------
DROP TABLE IF EXISTS `bar_rank`;
CREATE TABLE `bar_rank`  (
  `bid` int(0) NOT NULL,
  `rank_JSON` varchar(10000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  INDEX `bid_bar_rank`(`bid`) USING BTREE,
  CONSTRAINT `bid_bar_rank` FOREIGN KEY (`bid`) REFERENCES `bar` (`bid`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of bar_rank
-- ----------------------------
INSERT INTO `bar_rank` VALUES (1, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (2, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (3, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (4, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (5, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (6, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (7, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (8, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (9, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (10, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (11, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (12, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (13, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (14, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (15, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (16, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (17, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (18, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (19, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (20, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');
INSERT INTO `bar_rank` VALUES (27, '[{\"label\":\"初出茅庐\",\"level\":1,\"score\":0},{\"label\":\"初级粉丝\",\"level\":2,\"score\":15},{\"label\":\"中级粉丝\",\"level\":3,\"score\":40},{\"label\":\"高级粉丝\",\"level\":4,\"score\":100},{\"label\":\"活跃吧友\",\"level\":5,\"score\":200},{\"label\":\"核心吧友\",\"level\":6,\"score\":400},{\"label\":\"铁杆吧友\",\"level\":7,\"score\":600},{\"label\":\"知名人士\",\"level\":8,\"score\":1000},{\"label\":\"人气楷模\",\"level\":9,\"score\":1500},{\"label\":\"黄牌指导\",\"level\":10,\"score\":2000},{\"label\":\"意见领袖\",\"level\":11,\"score\":3000},{\"label\":\"意见领袖\",\"level\":12,\"score\":6000},{\"label\":\"意见领袖\",\"level\":13,\"score\":10000},{\"label\":\"意见领袖\",\"level\":14,\"score\":14000},{\"label\":\"意见领袖\",\"level\":15,\"score\":20000}]');

SET FOREIGN_KEY_CHECKS = 1;
